# Generated by Django 3.2.7 on 2021-09-29 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GenderName', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('UserName', models.CharField(blank=True, max_length=200, null=True)),
                ('BirthDay', models.DateField(blank=True, null=True)),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('IsMusician', models.BooleanField(default=False)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.user')),
            ],
        ),
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongName', models.CharField(blank=True, default='Unknow', max_length=200, null=True)),
                ('AvatarSong', models.ImageField(blank=True, null=True, upload_to='')),
                ('Views', models.IntegerField(blank=True, default=0, null=True)),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.user')),
                ('GenderSong', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Servicios.generomusical')),
            ],
        ),
    ]
