# Generated by Django 3.2.7 on 2021-09-14 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canciones',
            old_name='ArtistName',
            new_name='Artist',
        ),
        migrations.AlterField(
            model_name='canciones',
            name='GenderSong',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Servicios.generomusical'),
        ),
    ]
