# Generated by Django 3.2.7 on 2021-09-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0003_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='BirthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
