# Generated by Django 3.2.7 on 2021-09-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_alter_usuario_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='BirthDate',
            new_name='BirthDay',
        ),
    ]
