# Generated by Django 3.2.7 on 2021-09-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_generomusical_gendername'),
    ]

    operations = [
        migrations.AddField(
            model_name='canciones',
            name='Views',
            field=models.IntegerField(default=0),
        ),
    ]
