# Generated by Django 3.2.7 on 2021-09-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_canciones_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canciones',
            name='Views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
