# Generated by Django 3.2.7 on 2021-09-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0006_alter_canciones_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canciones',
            name='SongName',
            field=models.CharField(blank=True, default='Unknow', max_length=200, null=True),
        ),
    ]
